In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
b = np.array([(1.5,2,3),(4,5,6)], dtype=float)
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [7]:
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype=float)
c

array([[[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 3. ,  2. ,  1. ],
        [ 4. ,  5. ,  6. ]]])

In [9]:
np.zeros((3,4))


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
np.ones((2,3),dtype=float)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [16]:
d= np.arange(10,26,1)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [18]:
np.linspace(0,2,5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [20]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [28]:
np.random.random((5,2,3))

array([[[ 0.28198363,  0.29234839,  0.69824518],
        [ 0.39861491,  0.31422323,  0.87084244]],

       [[ 0.85389906,  0.80592194,  0.82708634],
        [ 0.29447376,  0.73336899,  0.22135838]],

       [[ 0.56799712,  0.84468678,  0.42866676],
        [ 0.22629205,  0.52771383,  0.88038955]],

       [[ 0.11267745,  0.33632467,  0.34004072],
        [ 0.70640217,  0.9136181 ,  0.20819115]],

       [[ 0.25095389,  0.1645927 ,  0.08716941],
        [ 0.64842619,  0.99738398,  0.12439264]]])

In [29]:
np.empty((2,3))

array([[ 0.35143486,  0.58602791,  0.12144439],
       [ 0.00825481,  0.44311859,  0.04401881]])

In [30]:
np.save('my_array',a)

In [31]:
np.savez('array.npz',a,b)

In [34]:
np.load('my_array.npy')


array([1, 2, 3])

In [36]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [37]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692])

In [39]:
a.dot(a)

14

In [40]:
a==b

array([[False,  True,  True],
       [False, False, False]], dtype=bool)

In [41]:
a<2

array([ True, False, False], dtype=bool)

In [42]:
np.array_equal(a,b)

False

In [51]:
a.cumsum(axis=0)

array([1, 3, 6], dtype=int32)

In [58]:
np.std(c)

1.6514934318838677

In [62]:
h=b.view()
h

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [65]:
a[0:2]

array([1, 2])

In [67]:
b[0:1,2]

array([ 3.])

In [72]:
b[:,:]

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [82]:
b[0,...]

array([ 1.5,  2. ,  3. ])

In [84]:
b[:1,1]

array([ 2.])

In [87]:
a[a<2]

array([1])

In [89]:
b[[0,1,1],[0,1,2]]

array([ 1.5,  5. ,  6. ])

In [92]:
b.T

array([[ 1.5,  4. ],
       [ 2. ,  5. ],
       [ 3. ,  6. ]])

In [97]:
g=a-b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [99]:
g.reshape(3,2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [101]:
np.vstack((a,b))

array([[ 1. ,  2. ,  3. ],
       [ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [102]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25])

In [106]:
np.r_[a,a]

array([1, 2, 3, 1, 2, 3])

In [109]:
np.hsplit(a,3)


[array([1]), array([2]), array([3])]

In [111]:
np.vsplit(c,2)

[array([[[ 1.5,  2. ,  3. ],
         [ 4. ,  5. ,  6. ]]]), array([[[ 3.,  2.,  1.],
         [ 4.,  5.,  6.]]])]